apiVersion: v1
kind: Service
metadata:
  name: kubernetes
  labels:
     app: kyrosbus
     project: infinity
spec:
  containers:
    - name: kyrosserver
      image: ananddocker18/kyrosbus:latest
      ports:
        - containerPort: 3000
