apiVersion: v1
kind: Service
metadata:
  name: kubernetes
spec:
  type: LoadBalancer
  selector:
    app: kyrosbus
  ports:
    - protocol: TCP
      port: 443
      targetPort: 6443
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyros-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kyrosbus
  template:
    metadata:
      labels:
        app: kyrosbus
    spec:
      containers:
        - name: kyrosserver
          image: ananddocker18/kyrosbus:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
